// contains a cleaned list of top search terms on wikipedia - gathered Dec 12 2022 - Jan 2 2023
const words = [
    'Demi Lovato', 'Elf film', 'Minneapolis', 'Presidential system', 'Leonard Cohen', 'Fashion design', 'Microsoft SQL Server', 'Gabriel García Márquez', 'Odyssey', 'List of colors: A-F', 'Board of directors', 'Lava', 'Sahrawi Arab Democratic Republic', 'United States Department of Defense', 'Church of England', 'Morgan Wallen', 'ITV (TV network)', 'West Bromwich Albion F.C.', 'Quantum entanglement', 'USB', 'Alphabet Inc.', 'Renault', 'ACF Fiorentina', 'Diane Lane', 'Royal Air Force', 'Medicare (United States)', 'Free agent', 'Random-access memory', 'Los Angeles Times', 'United States Soccer Federation', 'Linkin Park', 'Superman', 'Dream Theater', 'Köppen climate classification', 'Southampton F.C.', 'Intel', 'Conspiracy theory', 'Phoenix, Arizona', 'American Samoa', 'University of California, Los Angeles', 'San Diego', 'A cappella', 'World',
    'FIFA World Cup records and statistics', 'Houston', 'The Twelve Days of Christmas (song)', 'Kendrick Lamar', '2023 AFC Asian Cup', 'A. J. Brown', 'Aerosmith', 'Pixar', 'Function (mathematics)', 'Spider-Man: Into the Spider-Verse', 'Meta Platforms', 'Patent', 'Football pitch', 'The Magic Flute', 'Shin Ultraman', 'AM broadcasting', 'Al Gore', 'Suits (American TV series)', 'Work (physics)', 'Cleveland', 'Boeing 777', 'Reading', 'Giannis Antetokounmpo', 'The Elf on the Shelf', 'Value-added tax', 'Oldham Athletic A.F.C.', 'What a Wonderful World', "The Last of Us",
    'Lionel Messi', 'Festivus', 'The Specials', 'The Sound of Music (film)', "Newell's Old Boys", 'Reborn Rich', 'Christopher Plummer', 'Steve Cohen (businessman)', 'Index of Windows games (A)', 'Aliens (film)', 'Helen Mirren', 'S.S.C. Napoli', 'Club Atlético River Plate', 'Boca Juniors', 'Die Hard (film series)', 'A Charlie Brown Christmas', 'Aldous Huxley', 'Imran Khan', 'Pope Benedict XVI', 'To Kill a Mockingbird', 'Pokémon Ultimate Journeys: The Series', 'Siniša Mihajlović', 'Mickey Rooney', 'Characters of the DC Extended Universe', '2023 Africa Cup of Nations', "Catherine O'Hara", 'Richard Harris', 'Paulo Dybala', 'Martin McDonagh', "You're a Mean One, Mr. Grinch", 'John Lithgow', 'FA Trophy', 'White Christmas (song)', 'A Visit from St. Nicholas', 'The Year Without a Santa Claus', 'Joker: Folie à Deux', 'Leo Varadkar', 'Pinocchio', 'A Star Is Born (2018 film)', 'Hamza Yassin', 'A Christmas Carol (2009 film)', 'Warner Bros.', 'Succession to the British throne', 'M. Night Shyamalan', 'Ebenezer Scrooge', 'Ahmedabad', 'Bryan Cranston', 'Pope', 'A. R. Rahman', 'Leandro Paredes', 'Herbert Hoover', 'Debbie Reynolds', 'Julianne Moore', 'Betty White', 'Paolo Maldini', 'Edie Falco', 'Central African Republic', 'Baronet', 'Kiefer Sutherland', 'Microsoft Azure', 'NCAA Division I', 'A Bad Moms Christmas', 'Genus', 'Gerard Way', 'The Muppet Christmas Carol', 'The Dark Knight', 'AJ Styles', 'Frozen (2013 film)', 'Bardo, False Chronicle of a Handful of Truths', 'Prakash Raj', 'Robbie Coltrane', 'Sidney Poitier', 'Chuck Berry', 'Los Angeles Dodgers', 'Oakland Athletics', 'Watford F.C.', 'Skyfall', 'Sheffield United F.C.', 'Glossary of chess', 'Professional wrestling match types', 'Nigella Lawson', 'A Man Called Otto', 'Scrooge (1951 film)',
    'Alexandria Ocasio-Cortez', 'George R. R. Martin', 'Mathematical model', 'Richard Rodgers', "Groucho Marx","December 2022 North American winter storm","Indianapolis","Atal Bihari Vajpayee","Metropolitan statistical area","Alfred North Whitehead","Star Wars: The Force Awakens","John Elway","Buddy Holly","2023 World Junior Ice Hockey Championships","Paul Anka","Grease (film)","E.T. the Extra-Terrestrial","Niagara Falls","Die Hard with a Vengeance","Bette Davis","Forrest Gump","The Home Depot","Thomas Becket","Requiem for a Dream","Martha Stewart","Isaac Asimov","Michelle Williams (actress)","Rupert Grint","Axolotl","Gillian Anderson","Halle Berry","Savannah, Georgia","Variance","The Football Association","Board game","Straw man","Delta Air Lines","Rastafari","Fantastic Beasts (film series)","Bradford City A.F.C.","A Midsummer Night's Dream","Todd Rundgren","Marlo Thomas",
    "Beck","Flower","Jeff Beck","College football national championships in NCAA Division I FBS","President of India","Charlton Athletic F.C.","Georgia Bulldogs football","SoFi Stadium","Metro-Goldwyn-Mayer","The Raven","Claire Danes","Abbott Elementary","The Walking Dead (season 11)","Kliff Kingsbury","Graham Potter","A Quiet Place","Ronnie Wood","Ultraman (1966 TV series)","Federal Aviation Administration","Han dynasty","Alfred Russel Wallace","Mac operating systems","Pomerania","I Have a Dream","A24","Primetime Emmy Awards","The A.V. Club","Evan Peters","Christina Aguilera","List of EGOT winners","A. C. Bhaktivedanta Swami Prabhupada","Alan Cumming","Phineas and Ferb","Boy George","Belgian Pro League","Jessica Simpson","LL Cool J","Toyota Supra","James Herriot","Lulu (singer)","Academy Award for Best Actor","Compass","Community (TV series)","Miguel A. Núñez Jr.","Australian Broadcasting Corporation","Phoebe Waller-Bridge","The Flash (2014 TV series)",
    "The Last of Us (HBO)", "Panic! at the Disco","Berkshire Hathaway","Burns supper","Stephen A. Smith","Paul Ince","John Abraham","Forest Green Rovers F.C.","Lolita","Cyndi Lauper","Super Bowl LII","Abdel Fattah el-Sisi","Tommy Chong","Rabbit","Parks and Recreation","Academy Award for Best Actress","The Dark Side of the Moon","Saraswati","Sequoyah","Virginia Woolf","Ron Klain","Thandiwe Newton","Canberra","Circumference","List of Game of Thrones characters","Prime number","Alexander Skarsgård","KL Rahul","Rainbow","Alfred the Great","J. Cole","Hexagon","ESPN","Jennifer Garner","Zac Taylor","The Kid Laroi","Carlo Ancelotti","Julia Louis-Dreyfus","Paul Giamatti","Harley-Davidson","Cardiff City F.C.","Death of a Salesman","Los Angeles County, California",
    "Unicode subscripts and superscripts","Enclosed Alphanumerics","Blackboard bold","Fraktur","Ordinal indicator","Enclosed Alphanumeric Supplement","Los Angeles","United States","California","Muhammad Ali","ISBN","U.S. state","Singapore","Bachelor of Arts","Edgar Allan Poe","Saudi Arabia","Hong Kong","Madonna","Chicago","Arnold Schwarzenegger","Artificial intelligence","Abraham Lincoln","Steven Spielberg","George Washington","Taylor Swift","FC Barcelona","Wolfgang Amadeus Mozart","Elvis Presley","United Arab Emirates","Premier League","Manchester City F.C.","Philadelphia","Marvel Cinematic Universe","National Basketball Association","Jennifer Lopez","Martin Luther King Jr.","Marilyn Monroe","Albert Einstein","Lady Gaga","Tupac Shakur","Atlanta","John F. Kennedy","George VI","List of United States representatives from New York","Dubai","Egypt","Ilhan Omar","Nancy Pelosi","Cloud computing","Hawaii","German language","Frank Sinatra","Henry Kissinger","A.C. Milan","Cricket","Franklin D. Roosevelt","Ronald Reagan","Spotify", "Cher","Once Upon a Time in Hollywood","Los Angeles Rams","Theodore Roosevelt","Bill Clinton","Anita Baker","Zinedine Zidane","Anne Boleyn","Gene Hackman","Fenerbahçe S.K. (football)","Megan Mullally","Mötley Crüe","Lunch atop a Skyscraper","2026 FIFA World Cup","Harry Connick Jr.","Charles Lindbergh","ISO 216","Jill Biden","Tim Allen","Millet","FIFA","Eddie Howe",
    "Serie A","ASAP Rocky","Katy Perry","Gerald Ford","Jimmy Carter","Alexander Hamilton","Richard Nixon","Star Wars","Black hole","Lil Wayne","WWE","Willie Nelson","HTML","Lyndon B. Johnson","Thomas Jefferson","Naruto","NASA","Volodymyr Zelenskyy","John Adams","Rihanna","Lana Del Rey","Leeds United F.C.","A. J. McCarron","George Orwell","Email client","Olivia Newton-John","50 Cent","Detroit","Chadwick Boseman","Toyota","Andrew Jackson","Woodrow Wilson","The Lord of the Rings","List of sovereign states","Game of Thrones","Los Angeles Lakers","Wicket","Sigmund Freud","Ulysses S. Grant","Dwight D. Eisenhower","Columbia Pictures","Harry S. Truman","Oscar Wilde","A. P. J. Abdul Kalam","Temperature","Attention deficit hyperactivity disorder","Marcus Rashford","Benjamin Franklin","Neil Armstrong","Freddie Mercury","Radiohead","Catherine Zeta-Jones","Freemasonry","Jennifer Lawrence","List of municipalities in Michigan","Bernie Sanders","Year","Ernest Hemingway","FA Cup","Damian Lillard","Atlético Madrid","Tilde","Robin Williams","Ben Affleck","Rabindranath Tagore","ABBA","Christopher Columbus","Solar System","The Big Bang Theory","New Orleans","SZA","Bipolar disorder","Stan Lee","Kate Winslet","Glass Onion: A Knives Out Mystery","Binomial nomenclature","Kevin Bacon","William Shatner","IBM","Anno Domini","Kelsea Ballerini","Eastern Time Zone","Socrates","List of A Song of Ice and Fire characters","Burt Bacharach","Social media","Carrie Fisher","Hayden Panettiere","Lupang Hinirang","Banksy","Rowan Atkinson","Airbus A380","Minnesota","Mobile country code","List of United States counties and county equivalents","Minor League Baseball",
    "Grover Cleveland","Pittsburgh","A-side and B-side","Jewel (singer)","Blade Runner","Alan Turing","India women's national cricket team","Segunda División","Vanessa Hudgens","Juventus F.C.","Thomas Edison","Lamborghini","Adidas","Noam Chomsky","PinkPantheress","Warren G. Harding","RDFa","Gwen Stefani","Campeonato Brasileiro Série A","Lion","Flag of the United States","Sarah Silverman","Longitude","Coffee","The Silence of the Lambs (film)","A Song of Ice and Fire","William McKinley","Andrew Johnson","ISO 4217","John Quincy Adams","William Howard Taft","S.L. Benfica","Rita Ora","Alan Alda","Rugby union","Columbia University","Dallas","Billy Crudup","Geographic coordinate system","Texas A&M University","James Joyce","Encyclopedia","James A. Garfield","Constitution of the United States","Romelu Lukaku","El Camino: A Breaking Bad Movie","Evan Rachel Wood","Ray Kroc","ASEAN","NPR","Tomato","DNA","Real Betis","Eugene Levy","William Henry Harrison","AS Monaco FC",

];


// // contains a list of words that are not appropriate search terms that were gathered from wikipedia.
// const bannedWords = [
//     'Federal government of the United States', 'A', 'Google', 'Adolf Hitler', 'Amazon (company)', 'Donald Trump', '1', 'Democratic Party (United States)', 'Cannabis (drug)', 'Drake (musician)', 'Avatar (2009 film)', 'AFC Ajax', 'State of Palestine', 'Overtime (sports)', 'Fascism', 'HIV/AIDS',"Dmitry Medvedev", 'Vladimir Lenin', 'Prince (musician)',"1999 Aggie Bonfire collapse", "Leopold and Loeb",'Star Wars (film)', "United States Air Force", 'Grand Theft Auto V', "Family Guy", 'United States House Select Committee on the January 6 Attack',"Jeff Dunham", 'Wednesday (TV series)', 'Lockheed Martin F-22 Raptor', , 'Mestizo', 'Judaism',"Inglourious Basterds", "Al Jazeera", 'Fairchild Republic A-10 Thunderbolt II', 'Macau', 'List of ethnic slurs',"Lita (wrestler)", "Shiva Ayyadurai", 'Killed in action', , 'Genocide', "Ben Shapiro", 'Nuclear weapon',"Health care", 'Characters of the Marvel Cinematic Universe: A–L', 'AK-47', 'Hyderabad', "N.W.A","Beastie Boys", "Rajneesh", 'Hamilton (musical)', 'Bar',"M2 Browning",'Nineteen Eighty-Four', 'MF Doom', 'Masturbation', 'ALS', 'Troll (slang)', 'Anti-aircraft warfare',"Muhammad", '2026 FIFA World Cup qualification', 'Parsec', 'Mohamed Salah', 'McDonnell Douglas F/A-18 Hornet', "United States Marine Corps", "Afghanistan","Kanye West",'Find a Grave', 'Assassination', "NATO", "Edge (wrestler)", 'Squash (sport)', '2001: A Space Odyssey (film)', 'Lockheed F-117 Nighthawk', 'Chris Brown', 'List of colors: A–F', "Lord's Resistance Army", 'Casablanca (film)',"Jonas Brothers", 'A-League Men', 'Paracetamol', 'Nazi Party',"Opus Dei", "Logan Paul", 'Artemis', '0', 'The Wizard of Oz (1939 film)', 'Unitary state', 'Lenny Kravitz', 'Hermes', 'Capitalism', 'Capital punishment', 'Emmett Till', 'Boeing F/A-18E/F Super Hornet', 'Bosnian War', 'Noel Edmonds', 'United States Armed Forces', 'Suicide methods', 'Fred Thompson', 'God of War (2018 video game)', 'Kari Lake', 'Firearm', 'Rwandan genocide', 'Théo Hernandez', 'S.S.C. Bari', 'Socialism', 'Cortisol', 'The Silmarillion', 'Cybercrime', 'Hepatitis', 'Pregnancy', 'Helen of Troy', 'Cooperative', 'Hypersexuality', 'Libertarian Party (United States)', 'Master of Business Administration', 'League of Legends', 'COVID-19 pandemic in the United States', 'ʻOumuamua', 'Ayahuasca', 'Bavaria', "Did You Know That There's a Tunnel Under Ocean Blvd",
//     "Meningitis",'Deng Xiaoping', '2 Girls 1 Cup', 'Elf (film)', 'Saladin', 'Have Yourself a Merry Little Christmas', 'N/A', 'LTV A-7 Corsair II', "Messier 87", "Murder of Travis Alexander","B", ,"Dear Zachary: A Letter to a Son About His Father", "Gnosticism", ,"Abdul Qadeer Khan", "Royal Rumble match", "Surrogacy","That Time I Got Reincarnated as a Slime","Ultimate Fighting Championship","Fred Hampton",
//     'List of Star Wars films', 'Tree', 'List of NBA champions', 'Rod Stewart', 'Astronomical object', 'Anthony Bourdain', 'Jared Leto', 'Sam Taylor-Johnson', 'Luke Evans', 'Curling', 'Alisson', 'Sally Field', 'Romeo and Juliet', 'Raul Julia', 'Ray Liotta', 'List of colors: A-F', 'Michael Keaton', 'Business', 'Rafael Leão', '2001: A Space Odyssey', 'NAACP', 'Thiago Silva', 'Macbeth', 'Listed building', 'Birmingham', 'Liechtenstein', 'Language family', 'Epistemology', "Bachelor's degree", 'Constructed language', 'Reese Witherspoon', 'UK Singles Chart', 'Rwanda', 'A Christmas Story Christmas', 'Google Classroom', 'Archery', 'Quotation mark', 'Fiction', 'Wrexham A.F.C.', 'Ice Cube', 'Casablanca', 'Running back', 'List of common misconceptions', 'Victoria and Albert Museum', 'Mel Brooks', 'Sumo', 'The Cure', 'LA Galaxy', 'Blackpool F.C.', 'AFC Bournemouth', 'Los Angeles Angels', 'Stellar classification', 'Clarinet', 'Pathology', 'LVMH', 'A.S. Roma', 'Midwestern United States', 'Abu Dhabi', 'United States Census Bureau', 'Theatre', 'Recording Industry Association of America', 'Bee Gees', 'Maggie Smith', 'The Wizard of Oz 1939 film', 'The Boys TV Series', 'José Mourinho', 'Viola Davis', 'Patti Smith', 'Amazon Standard Identification Number', 'Young adult fiction', 'Wu-Tang Clan', 'A Certain Magical Index', 'Nun', 'Master of Arts', 'Two and a Half Men', 'Michael J. Fox', 'Game', 'Sunderland A.F.C.', 'Swansea City A.F.C.', 'Metaphor', 'Frank Lloyd Wright', 'Grimes', 'Calvin Coolidge', 'Muhammad Ali Jinnah',
//     'SpongeBob SquarePants', 'New York Yankees', "Lupita Nyong'o", "Schrödinger's cat", 'United States Declaration of Independence', 'Pulp Fiction', 'Master of Arts', 'Two and a Half Men', 'HBO', 'Boiling point', 'Rajendra Prasad', 'RCA Records', 'Chicago Cubs', 'Renée Zellweger', 'God of War 2018 video game', 'Shane MacGowan', 'Pentatonix', 'Rugby league', 'Empress Elisabeth of Austria', 'Electronic Arts', 'Theo Hernandez', 'Diameter', 'Momentum', 'Scanning electron microscope', 'Circle', 'Colin Firth', 'Massachusetts Institute of Technology', 'Hull City A.F.C.', 'Magnet', 'Oxford English Dictionary', 'Linda Ronstadt', 'Pluto', 'Function mathematics', 'Middlesbrough F.C.', 'Baal', 'Vernacular', 'Mean', 'Central Intelligence Agency', 'List of Young Sheldon episodes', 'Creedence Clearwater Revival', 'Oreo', 'White', 'Empirical evidence', 'Bob Iger', 'Sahrawi Arab Democratic Republic', 'Presidential system', 'Fashion design', 'Libertarian Party United States', 'Order of Australia', '2012 Summer Olympics', 'United States Department of Defense', 'Squash sport', 'Morgan Wallen', 'Oklahoma City', 'Motown', 'ITV TV network', 'Piano', 'Insurance', 'National Collegiate Athletic Association', 'Nanotechnology', 'Colin Jost', 'Royal Air Force', 'Medicare United States', 'Tetrahedron', 'Free agent', "Gulliver's Travels", 'Ruhollah Khomeini', 'Lee Harvey Oswald', 'Russell Crowe', 'Logistic regression', 'Country',

// ];


// async function searchWikipedia(searchQuery) {
//     const endpoint = `https://en.wikipedia.org/w/api.php?action=query&list=search&prop=info&inprop=url&utf8=&format=json&origin=*&srlimit=500&srsearch=${searchQuery}`;
//     const response = await fetch(endpoint);
//     if (!response.ok) {
//       throw Error(response.statusText);
//     }
//     const json = await response.json();
//     return json.query.search;
//   }


// try {
//     // Initialize an empty array to store search results
//     let wordsList = []
//     let searchQuery = "a";
//     // Call the searchWikipedia function and store the results in a variable
//     const results = await searchWikipedia(searchQuery);
  
//     // Iterate over the search results
//     results.forEach(term => {
//         // console.log(term.title);
//         if (!words.includes(term.title) && !bannedWords.includes(term.title)) { // if new term is not already included in the official list and has not already been banned, add it to list of possible new terms
//             wordsList.push(term.title);
//         } else { // Otherwise, the current search result is already in the list or has been banned, so do nothing
//             // console.log(term.title + " is already in the list of search terms");
//         }
        
//     });
//     // console.log(results);
//     // wordsList = wordsList.slice(0, 40);
//     console.table(JSON.stringify(wordsList));

// } catch (err) {
  
//     console.log(err);
  
//     alert('Failed to search wikipedia');
  
// }

// export the list of official words, to be used in popup.js
export {words};